import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Header from '../components/Header';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" rel="stylesheet"></link>
      </Head>
      <Navbar/>
      <Header/>
    </>
  )
}

export default Home
